### ISSUE TITLE
Had to add 'use strict'; to prodserver.js

### ISSUE THREAD

**Issue by gregbown** [qdouble/angular-webpack2-starter#139]
Really minor issue running prodserver, just in case someone else encounters it.  I just modified my local prodserver.js by adding 'use strict'; to resolve it.  Awesome work, thank you.

C:\..\angular-2-webpack-2\angular-webpack2-starter\prodserver.js:21
let e2e;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:429:10)
    at startup (node.js:139:18)
    at node.js:999:3

**Comment by qdouble** [comment]
Thanks for letting me know, add it here: https://github.com/qdouble/angular-webpack2-starter/commit/a891fa9896b6cd36fbabf55e6ae903f2c1c1f697
