### ISSUE TITLE
Error on WebPack Task Runner / cmd

### ISSUE THREAD

**Issue by wizardnet972** [qdouble/angular-webpack2-starter#146]
Hi,

need help here please,

I use  [WebPack Task Runner](https://visualstudiogallery.msdn.microsoft.com/5497fd10-b1ba-474c-8991-1438ae47012a) to run the project from visual studio 2015,

same as running from cmd:
`webpack -d`

But I getting error:

```
C:\code\angular2-webpack\webpack.config.ts:20
  DllReferencePlugin,
               ^
TypeError: Cannot read property 'includes' of undefined
    at Object.<anonymous> (c:\code\angular2-webpack\webpack.config.ts:20:16)
    at Module._compile (module.js:570:32)
    at Module.m._compile (c:\code\angular2-webpack\node_modules\ts-node\src\index.ts:403:23)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (c:\code\angular2-webpack\node_modules\ts-node\src\index.ts:406:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (C:\Users\wizardnet972\AppData\Roaming\npm\node_modules\webpack\bin\convert-argv.js:80:13)
    at Object.<anonymous> (C:\Users\wizardnet972\AppData\Roaming\npm\node_modules\webpack\bin\webpack.js:39:40)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by qdouble** [comment]
@wizardnet972 this is because the EVENT constant is based on which script you run with npm/yarn... to fix, you could just put something like:
```const EVENT = process.env.npm_lifecycle_event || '';```
or some other default string like 'prod' or 'aot:prod'

**Comment by qdouble** [comment]
@wizardnet972 just added a commit that should address this as well: https://github.com/qdouble/angular-webpack2-starter/commit/2d5aeac66de1e2f50914c6a83294628d298270c0

**Comment by wizardnet972** [comment]
Yes. Thank you @qdouble :)
