### ISSUE TITLE
Can't run universal/universal:aot after build

### ISSUE THREAD

**Issue by nampdn** [qdouble/angular-webpack2-starter#167]
Hi, I can build/run aot mode as normal, but not for the universal mode.
Here is the log:

```
Error: listen EADDRINUSE :::8888
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1376:9)
    at Function.listen (C:\@Projects\@various\angular-webpack2-starter-aot\node_modules\express\lib\application.js:617:24)
    at Object.startServer (C:\@Projects\@various\angular-webpack2-starter-aot\node_modules\webpack-bundle-analyzer\lib\viewer.js:57:14)
    at BundleAnalyzerPlugin.startAnalyzerServer (C:\@Projects\@various\angular-webpack2-starter-aot\node_modules\webpack-bundle-analyzer\lib\BundleAnalyzerPlugin.js:78:12)
    at analyzeFn (C:\@Projects\@various\angular-webpack2-starter-aot\node_modules\webpack-bundle-analyzer\lib\BundleAnalyzerPlugin.js:57:24)
    at Timeout._onTimeout (C:\@Projects\@various\angular-webpack2-starter-aot\node_modules\webpack-bundle-analyzer\lib\BundleAnalyzerPlugin.js:69:11)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

I can make sure that the port 8888 is not in use in my computer

**Comment by DzmitryShylovich** [comment]
Try to disable BundleAnalyzerPlugin

**Comment by nampdn** [comment]
@DzmitryShylovich You're so kind and so cute, I did it. Thanks

**Comment by qdouble** [comment]
I've changed the port for the analyzer here so it'd be less likely to have conflicts: https://github.com/qdouble/angular-webpack2-starter/commit/ce7b323bc3ed17347d9f5c50261177a6a16773a9

**Comment by John0x** [comment]
@qdouble you should consider that webpack will probalby try to rerun the analyzer everytime a change happens which will probably lead to a crash since the port will still be in use.

**Comment by qdouble** [comment]
@John0x It doesn't run when in dev mode, it's only there for production builds.

**Comment by John0x** [comment]
@qdouble but wouldn't it make sense to put it into dev mode since it's a dev task and not a production related?

**Comment by qdouble** [comment]
@John0x The purpose of the plugin is to tell much space different modules are adding to your app, the figures won't really be meaningful unless you're analyzing the production build.
