### ISSUE TITLE
"yarn run server:prod" fails

### ISSUE THREAD

**Issue by ricricucit** [qdouble/angular-webpack2-starter#188]
Clean install fails (watching?) running `yarn run server:prod`

````
...
````
````
Webpack Bundle Analyzer is started at http://localhost:5000
Use Ctrl+C to close it



Error: listen EADDRINUSE :::5000
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1376:9)
    at Function.listen (/Applications/MAMP/htdocs/angular-webpack2-starter/node_modules/express/lib/application.js:617:24)
    at Object.startServer (/Applications/MAMP/htdocs/angular-webpack2-starter/node_modules/webpack-bundle-analyzer/lib/viewer.js:60:14)
    at BundleAnalyzerPlugin.startAnalyzerServer (/Applications/MAMP/htdocs/angular-webpack2-starter/node_modules/webpack-bundle-analyzer/lib/BundleAnalyzerPlugin.js:91:12)
    at /Applications/MAMP/htdocs/angular-webpack2-starter/node_modules/webpack-bundle-analyzer/lib/BundleAnalyzerPlugin.js:56:24
    at /Applications/MAMP/htdocs/angular-webpack2-starter/node_modules/webpack-bundle-analyzer/lib/BundleAnalyzerPlugin.js:69:20
    at Array.forEach (native)
    at Immediate.<anonymous> (/Applications/MAMP/htdocs/angular-webpack2-starter/node_modules/webpack-bundle-analyzer/lib/BundleAnalyzerPlugin.js:68:19)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/{{user}}/.nvm/versions/node/v7.0.0/bin/node" "/Applications/MAMP/htdocs/angular-webpack2-starter/node_modules/.bin/npm" "run" "build:prod" "--" "--watch"
npm ERR! node v7.0.0
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE
npm ERR! angular-webpack2-starter@1.14.0 build:prod: `npm run clean:dist && npm run sass && webpack "--watch"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-webpack2-starter@1.14.0 build:prod script 'npm run clean:dist && npm run sass && webpack "--watch"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-webpack2-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean:dist && npm run sass && webpack "--watch"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-webpack2-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-webpack2-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Applications/MAMP/htdocs/angular-webpack2-starter/npm-debug.log
ERROR: "build:prod -- --watch" exited with 1.
````

**npm-debug.log**

````
0 info it worked if it ends with ok
1 verbose cli [ '/Users/{{user}}/.nvm/versions/node/v7.0.0/bin/node',
1 verbose cli   '/Applications/MAMP/htdocs/angular-webpack2-starter/node_modules/.bin/npm',
1 verbose cli   'run',
1 verbose cli   'watch:prod' ]
2 info using npm@4.0.3
3 info using node@v7.0.0
4 verbose run-script [ 'prewatch:prod', 'watch:prod', 'postwatch:prod' ]
5 info lifecycle angular-webpack2-starter@1.14.0~prewatch:prod: angular-webpack2-starter@1.14.0
6 silly lifecycle angular-webpack2-starter@1.14.0~prewatch:prod: no script for prewatch:prod, continuing
7 info lifecycle angular-webpack2-starter@1.14.0~watch:prod: angular-webpack2-starter@1.14.0
8 verbose lifecycle angular-webpack2-starter@1.14.0~watch:prod: unsafe-perm in lifecycle true
9 verbose lifecycle angular-webpack2-starter@1.14.0~watch:prod: PATH: /Applications/MAMP/htdocs/angular-webpack2-starter/node_modules/npm/bin/node-gyp-bin:/Applications/MAMP/htdocs/angular-webpack2-starter/node_modules/.bin:/Applications/MAMP/htdocs/angular-webpack2-starter/node_modules/.bin:/Users/{{user}}/.config/yarn/link/node_modules/.bin:/Applications/MAMP/htdocs/angular-webpack2-starter/node_modules/.bin:/Users/{{user}}/.config/yarn/link/node_modules/.bin:/usr/local/Cellar/yarn/0.17.9/libexec/lib/node_modules/yarn/bin/node-gyp-bin:/Users/{{user}}/.nvm/versions/node/v7.0.0/bin:/Applications/MAMP/bin/php/php5.6.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/{{user}}/.android-sdk-macosx/platform-tools/
10 verbose lifecycle angular-webpack2-starter@1.14.0~watch:prod: CWD: /Applications/MAMP/htdocs/angular-webpack2-starter
11 silly lifecycle angular-webpack2-starter@1.14.0~watch:prod: Args: [ '-c', 'npm-run-all -p -r "build:prod -- --watch" sass:watch' ]
12 silly lifecycle angular-webpack2-starter@1.14.0~watch:prod: Returned: code: 1  signal: null
13 info lifecycle angular-webpack2-starter@1.14.0~watch:prod: Failed to exec watch:prod script
14 verbose stack Error: angular-webpack2-starter@1.14.0 watch:prod: `npm-run-all -p -r "build:prod -- --watch" sass:watch`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Applications/MAMP/htdocs/angular-webpack2-starter/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/Applications/MAMP/htdocs/angular-webpack2-starter/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid angular-webpack2-starter@1.14.0
16 verbose cwd /Applications/MAMP/htdocs/angular-webpack2-starter
17 error Darwin 16.1.0
18 error argv "/Users/{{user}}/.nvm/versions/node/v7.0.0/bin/node" "/Applications/MAMP/htdocs/angular-webpack2-starter/node_modules/.bin/npm" "run" "watch:prod"
19 error node v7.0.0
20 error npm  v4.0.3
21 error code ELIFECYCLE
22 error angular-webpack2-starter@1.14.0 watch:prod: `npm-run-all -p -r "build:prod -- --watch" sass:watch`
22 error Exit status 1
23 error Failed at the angular-webpack2-starter@1.14.0 watch:prod script 'npm-run-all -p -r "build:prod -- --watch" sass:watch'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular-webpack2-starter package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm-run-all -p -r "build:prod -- --watch" sass:watch
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular-webpack2-starter
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular-webpack2-starter
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

````

**Comment by DzmitryShylovich** [comment]
> EADDRINUSE :::5000

change Webpack Bundle Analyzer port or disable it

**Comment by ricricucit** [comment]
Sorry, forgot to mention that I've tried with different ports...same result.
Obviously works fine when disabling it.

**Comment by qdouble** [comment]
@ricricucit this https://github.com/qdouble/angular-webpack2-starter/commit/1f41126b95a495d36b4d6078638ed116fb1da677 should deal with that issue
