### ISSUE TITLE
`npm run lint` has error occured "Cannot read property 'parse' of undefined"

### ISSUE THREAD

**Issue by balmychan** [qdouble/angular-webpack2-starter#226]
After comitted 6d2d820, `npm run lint` command has error occured.

```
$ npm run lint

> angular-webpack2-starter@1.14.0 lint C:\repos\angular-webpack2-starter
> npm run tslint "src/app/**/*.ts"


> angular-webpack2-starter@1.14.0 tslint C:\repos\angular-webpack2-starter
> tslint "src/app/**/*.ts"

C:\Repos\angular-webpack2-starter\node_modules\tslint\lib\runner.js:117
            throw error;
            ^

TypeError: Cannot read property 'parse' of undefined
    at SelectorValidatorWalker.extractMainSelector (C:\repos\angular-webpack2-starter\node_modules\codelyzer\selectorNameBase.js:152:36 )
    at C:\repos\angular-webpack2-starter\node_modules\codelyzer\selectorNameBase.js:119:39
    at Array.forEach (native)
    at SelectorValidatorWalker.validateSelector (C:\repos\angular-webpack2-starter\node_modules\codelyzer\selectorNameBase.js:118:18)
    at SelectorValidatorWalker.validateDecorator (C:\repos\angular-webpack2-starter\node_modules\codelyzer\selectorNameBase.js:110:18)
    at Array.forEach (native)
    at SelectorValidatorWalker.visitClassDeclaration (C:\repos\angular-webpack2-starter\node_modules\codelyzer\selectorNameBase.js:100: 14)
    at SelectorValidatorWalker.SyntaxWalker.visitNode (C:\repos\angular-webpack2-starter\node_modules\tslint\lib\language\walker\syntax Walker.js:304:22)
    at C:\repos\angular-webpack2-starter\node_modules\tslint\lib\language\walker\syntaxWalker.js:517:63
    at visitEachNode (C:\repos\angular-webpack2-starter\node_modules\typescript\lib\typescript.js:8343:30)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "tslint" "src /app/**/*.ts"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular-webpack2-starter@1.14.0 tslint: `tslint "src/app/**/*.ts"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-webpack2-starter@1.14.0 tslint script 'tslint "src/app/**/*.ts"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-webpack2-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tslint "src/app/**/*.ts"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-webpack2-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-webpack2-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\repos\angular-webpack2-starter\npm-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular-webpack2-starter@1.14.0 lint: `npm run tslint "src/app/**/*.ts" `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-webpack2-starter@1.14.0 lint script 'npm run tslint "src/app/**/*.ts" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-webpack2-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run tslint "src/app/**/*.ts"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-webpack2-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-webpack2-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\repos\angular-webpack2-starter\npm-debug.log
```

because codelyzer@2.0.0-beta.3 depends angular@compiler's CssSelector method.
maybe need to upgrade angular2 version to more 2.1.0

**Comment by qdouble** [comment]
Okay, I've reverted it on the universal branches: https://github.com/qdouble/angular-webpack2-starter/commit/9823b7cc95faf78577ffe62787ad4d8aa31fcb66 

Angular isn't doing a good job of keeping Universal up to speed with core, so I've mostly switched to using just AOT in my own projects.
