### ISSUE TITLE
Universal does not work

### ISSUE THREAD

**Issue by akhatri** [qdouble/angular-webpack2-starter#262]
I have recently migrated to your starter pack for universal support. Looks really good but unfortunately I have issues when running the app in production mode. The app works fine when I run either 'yarn start' and `yarn run start:hmr`

I am guessing we need to run `yarn run build` to compile all assets to make it production ready. This works on the CLI but I just see the Webpack Analyzer Bundle (not sure if that is an error - screenshot attached).

I then run `yarn run universal` the CLI does not throw errors but there are console errors with broken reference files to the css and js. (screenshot attached)

Also, when I try to load a new link via routes I get no content found (screenshot attached). 

I have seen the folder for server and it looks okay to me with the css and js files being populated (screenshot attached)

I'm not sure what I am missing but it appears to be some setting. I need universal mode to work as our app is going to be dependent on strong SEO. any help appreciated.

![webpack bundle analyzer](https://cloud.githubusercontent.com/assets/2246544/23831301/7502a382-0772-11e7-952b-cb98ab6cd23a.PNG)
![console error](https://cloud.githubusercontent.com/assets/2246544/23831300/7502526a-0772-11e7-904f-aa4ed46e423b.PNG)
![routing error](https://cloud.githubusercontent.com/assets/2246544/23831299/75024144-0772-11e7-998a-b7561152b45b.PNG)
![server folder structure](https://cloud.githubusercontent.com/assets/2246544/23831298/7501eae6-0772-11e7-8c2b-33fdec541bd3.PNG)

**Comment by qdouble** [comment]
As stated in other issues, I will not be touching Universal branches until it's updated to work properly with angular 4.0. Universal lags behind the main angular branches so it breaks more and more with every angular update as it's not tested against core.

**Comment by Phoscur** [comment]
@qdouble can you add a shrinkwrap for the time being please to freeze the dependencies working with eachother?

**Comment by fdambrosio** [comment]
will be updated to Angular 4?

**Comment by matt328** [comment]
I have been working on this [here](https://github.com/matt328/angular-webpack2-starter), but am pretty stumped as to the best way to fix this error:

```
/Users/matt/Projects/Personal/angular-universal/angular-webpack2-starter/node_modules/@ngrx/store/src/dispatcher.js:6
import { BehaviorSubject } from 'rxjs/BehaviorSubject';
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.83 (/Users/matt/Projects/Personal/angular-universal/angular-webpack2-starter/dist/server/index.js:1:127267)
    at e (/Users/matt/Projects/Personal/angular-universal/angular-webpack2-starter/dist/server/index.js:1:177)
```

I know why it is happening, ngrx has some .js files that have es6 syntax in them and the build system isn't transpiling that to es5.  [This stackoverflow post](http://stackoverflow.com/questions/39546997/syntaxerror-unexpected-token-export) recommends either using babel, using webpack, or yelling at the ngrx developers.  The webpack suggestion is probably where the solution is, but I'm still not quite familiar enough with how this starter is using for AOT/Universal.

**Comment by matt328** [comment]
I have gotten a little further, but due to [this issue](https://github.com/angular/material2/issues/308) I don't think I can go any further since it seems Material 2 just plain does not work yet with Angular Universal, and won't officially until 'around 4.1.x'.

Unofficially there are a few workarounds that do work as mentioned [here](https://github.com/angular/material2/issues/308#issuecomment-288808009).

**Comment by qdouble** [comment]
@fdambrosio yes, I will update the universal (or whatever they rename it to) branches when it is somewhat stable... doesn't seem to make sense to mess with it right now
