### ISSUE TITLE
yarn compilation error at webpack

### ISSUE THREAD

**Issue by jervtub** [qdouble/angular-webpack2-starter#264]
More specifically, I receive the compilation error at the `webpack` subcommand.

> D:\Sandboxes\angular-webpack2-starter\node_modules\ts-node\src\index.ts:312
    throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
                                        ^
 D:\Sandboxes\angular-webpack2-starter\node_modules\ts-node\src\index.ts:312
          throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
                ^
TSError: ⨯ Unable to compile TypeScript
webpack.config.ts (116,38): Property 'assign' does not exist on type 'ObjectConstructor'. (2339)
webpack.config.ts (214,38): Property 'assign' does not exist on type 'ObjectConstructor'. (2339)
webpack.config.ts (291,12): Property 'assign' does not exist on type 'ObjectConstructor'. (2339)
    at getOutput (D:\Sandboxes\angular-webpack2-starter\node_modules\ts-node\src\index.ts:312:17)
    at D:\Sandboxes\angular-webpack2-starter\node_modules\ts-node\src\index.ts:343:18
    at Object.compile (D:\Sandboxes\angular-webpack2-starter\node_modules\ts-node\src\index.ts:476:19)
    at Module.m._compile (D:\Sandboxes\angular-webpack2-starter\node_modules\ts-node\src\index.ts:406:44)
    at Module._extensions..js (module.js:579:10)
    at require.extensions.(anonymous function) (D:\Sandboxes\angular-webpack2-starter\node_modules\ts-node\src\index.ts:409:12)
    at Object.require.extensions.(anonymous function) [as .ts] (D:\Sandboxes\LookingGlass\node_modules\ts-node\src\index.ts:409:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
TSError: ⨯ Unable to compile TypeScript
webpack.config.ts (116,38): Property 'assign' does not exist on type 'ObjectConstructor'. (2339)
webpack.config.ts (214,38): Property 'assign' does not exist on type 'ObjectConstructor'. (2339)
webpack.config.ts (291,12): Property 'assign' does not exist on type 'ObjectConstructor'. (2339)
    at getOutput (D:\Sandboxes\angular-webpack2-starter\node_modules\ts-node\src\index.ts:312:17)
    at D:\Sandboxes\angular-webpack2-starter\node_modules\ts-node\src\index.ts:343:18
    at Object.compile (D:\Sandboxes\angular-webpack2-starter\node_modules\ts-node\src\index.ts:476:19)
    at Module.m._compile (D:\Sandboxes\angular-webpack2-starter\node_modules\ts-node\src\index.ts:406:44)
    at Module._extensions..js (module.js:579:10)
    at require.extensions.(anonymous function) (D:\Sandboxes\angular-webpack2-starter\node_modules\ts-node\src\index.ts:409:12)
    at Object.require.extensions.(anonymous function) [as .ts] (D:\Sandboxes\LookingGlass\node_modules\ts-node\src\index.ts:409:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by KukyNekoi** [comment]
Use this tsconfig.webpack.json.

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es2015", "dom"],
    "noEmitHelpers": true,
    "skipDefaultLibCheck": true,
    "pretty": true,
    "sourceMap": true,
    "strictNullChecks": false,
    "typeRoots": [
      "node_modules/@types"
    ]
  },
  "exclude": [
    "node_modules",
    "compiled",
    "e2e/**/*.ts",
    "src/**/*.spec.ts",
    "src/server.ts",
    "src/main.browser.aot.ts"
  ],
  "awesomeTypescriptLoaderOptions": {
    "useWebpackText": true,
    "forkChecker": true,
    "useCache": true
  },
  "compileOnSave": false,
  "buildOnSave": false,
  "atom": { "rewriteTsconfig": false }
}

```
