### ISSUE TITLE
Universal is not working OOTB...

### ISSUE THREAD

**Issue by sneridagh** [qdouble/angular-webpack2-starter#267]
This is the stacktrace:

```
[nodemon] starting `node dist/server/index.js`
/Development/kitconcept/blogssr/node_modules/@angular/material/material.umd.js:2028
var hasV8BreakIterator = (window.Intl && window.Intl.v8BreakIterator);
                                      ^

ReferenceError: window is not defined
    at /Development/kitconcept/blogssr/node_modules/@angular/material/material.umd.js:2028:39
    at c (/Development/kitconcept/blogssr/node_modules/@angular/material/material.umd.js:2:68)
    at Object.<anonymous> (/Development/kitconcept/blogssr/node_modules/@angular/material/material.umd.js:5:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by qdouble** [comment]
closing... universal branches will be updated when it's stable in Angular 4
